#! /usr/bin/python
from SimpleCV import Image, Camera, Color
#cam = Camera()
#img = cam.getImage()
#img.save("lunar1.jpg")
pruebalunar=Image("lunar5nico.png")
lunargris=pruebalunar.grayscale()
lunargris.save("fotoslunarprurba.png")
(red,green,blue)=pruebalunar.splitChannels(False)
red.save("fotoenrojo.png")
green.save("fotoenverde.png")
blue.save("fotoenazul.png")
prueba69=lunargris.binarize()
mancha=prueba69.findBlobs()
mancha.show()
brown_distance=pruebalunar.colorDistance(Color.BLACK).invert()
blobs2_=brown_distance.findBlobs()
brown_distance.show()
#lineas=pruebalunar.findLines()
#lineas.draw(width=3)
#pruebalunar.show()
circles=pruebalunar.findCircle(canny=100,thresh=250,distance=15)
circles=circles.sortArea()
circles.draw(width=2)
img_with_circles= pruebalunar.applyLayers()
edges_in_image= pruebalunar.edges(t2=200)
final=pruebalunar.sideBySide(edges_in_image.sideBySide(img_with_circles)).scale(0.5)
final.show()
final.save("porfavorguardate.png")
